### PR TITLE
fix osx build for clang with new conda compiler stack

### PR DESCRIPTION
**Pull request by k-dominik**
lemon wouldn't build with the current compiler-stack and fail with something like

```C++
n file included from /Users/vsts/agent/2.148.1/work/1/a/miniconda/conda-bld/lemon_1552894398158/work/test/bfs_test.cc:23:
In file included from /Users/vsts/agent/2.148.1/work/1/a/miniconda/conda-bld/lemon_1552894398158/work/lemon/bfs.h:31:
/Users/vsts/agent/2.148.1/work/1/a/miniconda/conda-bld/lemon_1552894398158/work/lemon/path.h:231:24: error: no viable conversion from 'typename PredMapPath<Digraph, NodeMap<Arc> >::RevArcIt' to 'value_type' (aka 'lemon::concepts::Digraph::Arc')
        head.push_back(it);
                       ^~
/Users/vsts/agent/2.148.1/work/1/a/miniconda/conda-bld/lemon_1552894398158/work/lemon/path.h:1017:12: note: in instantiation of function template specialization 'lemon::Path<lemon::concepts::Digraph>::buildRev<lemon::PredMapPath<lemon::concepts::Digraph, lemon::concepts::Digraph::NodeMap<lemon::concepts::Digraph::Arc> > >' requested here
        to.buildRev(from);
           ^
/Users/vsts/agent/2.148.1/work/1/a/miniconda/conda-bld/lemon_1552894398158/work/lemon/path.h:1033:45: note: in instantiation of member function 'lemon::_path_bits::PathCopySelectorBackward<lemon::PredMapPath<lemon::concepts::Digraph, lemon::concepts::Digraph::NodeMap<lemon::concepts::Digraph::Arc> >, lemon::Path<lemon::concepts::Digraph>, true>::copy' requested here
        PathCopySelectorBackward<From, To>::copy(from, to);
                                            ^
/Users/vsts/agent/2.148.1/work/1/a/miniconda/conda-bld/lemon_1552894398158/work/lemon/path.h:1046:45: note: in instantiation of member function 'lemon::_path_bits::PathCopySelector<lemon::PredMapPath<lemon::concepts::Digraph, lemon::concepts::Digraph::NodeMap<lemon::concepts::Digraph::Arc> >, lemon::Path<lemon::concepts::Digraph>, true>::copy' requested here
    _path_bits::PathCopySelector<From, To>::copy(from, to);
                                            ^
/Users/vsts/agent/2.148.1/work/1/a/miniconda/conda-bld/lemon_1552894398158/work/lemon/path.h:94:7: note: in instantiation of function template specialization 'lemon::pathCopy<lemon::PredMapPath<lemon::concepts::Digraph, lemon::concepts::Digraph::NodeMap<lemon::concepts::Digraph::Arc> >, lemon::Path<lemon::concepts::Digraph> >' requested here
      pathCopy(cpath, *this);
      ^
/Users/vsts/agent/2.148.1/work/1/a/miniconda/conda-bld/lemon_1552894398158/work/test/bfs_test.cc:98:8: note: in instantiation of function template specialization 'lemon::Path<lemon::concepts::Digraph>::operator=<lemon::PredMapPath<lemon::concepts::Digraph, lemon::concepts::Digraph::NodeMap<lemon::concepts::Digraph::Arc> > >' requested here
    pp = const_bfs_test.path(t);
       ^
/Users/vsts/agent/2.148.1/work/1/a/miniconda/conda-bld/lemon_1552894398158/work/lemon/concepts/digraph.h:167:9: note: candidate constructor not viable: no known conversion from 'typename PredMapPath<Digraph, NodeMap<Arc> >::RevArcIt' to 'const lemon::concepts::Digraph::Arc &' for 1st argument
        Arc(const Arc&) { }
        ^
/Users/vsts/agent/2.148.1/work/1/a/miniconda/conda-bld/lemon_1552894398158/work/lemon/concepts/digraph.h:172:9: note: candidate constructor not viable: no known conversion from 'typename PredMapPath<Digraph, NodeMap<Arc> >::RevArcIt' to 'lemon::Invalid' for 1st argument
        Arc(Invalid) { }
        ^
/Users/vsts/agent/2.148.1/work/1/a/miniconda/conda-bld/lemon_1552894398158/work/lemon/bits/path_dump.h:64:7: note: candidate function
      operator const typename Digraph::Arc() const {
      ^
/Users/vsts/agent/2.148.1/work/1/a/miniconda/conda-bld/lemon_1552894398158/_build_env/bin/../include/c++/v1/vector:678:59: note: passing argument to parameter '__x' here
    _LIBCPP_INLINE_VISIBILITY void push_back(value_type&& __x);
                                                         
```

during building of the tests. A related problem can be found [here on stackoverflow](https://stackoverflow.com/a/33641030).
Together with @DerThorsten (thx again!) we added a patch that fixes the build under osx.

Is it safe to assume that the erroneous Azure builds for Win are nothing to worry about (since appveyor passes)?

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by k-dominik** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
We made some changes to how re-rendering works, which requires changes in `master`. I've triggered a bot re-rendering in PR ( https://github.com/conda-forge/lemon-feedstock/pull/12 ). Maybe that can be merged into this PR?

**Comment by k-dominik** [comment]
> We made some changes to how re-rendering works, which requires changes in `master`. I've triggered a bot re-rendering in PR ( #12 ). Maybe that can be merged into this PR?

I can also rebase/force-push the "actual patch" without all the historic smithy fluff on current master for this PR, or do you prefer me merging master into this?

**Comment by jakirkham** [comment]
It’s probably simpler to just merge it in.

**Comment by k-dominik** [comment]
@conda-forge-admin, please re-render.

**Pull request merged**
