### PR TITLE
fix win build: debug -> release

### LINKED ISSUE #15: lemon currently shipped as debug build on windows
see [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=184711&view=logs&j=f97ca392-d626-52d0-4b2e-4b27aa319a77&t=7b750183-140d-50ae-3ee1-cbef6218bdf6&l=1272) on azure pipelines

In `cmake --build . --config Release --target install` the `--config` option seems to be ignored.

### PR DESCRIPTION
**Pull request by k-dominik**
pushing some commits in lieu of a VS debugging env

will at some point hopefully fix #15 

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by k-dominik** [comment]
no clue how to verify this remotely :D, I guess I'll set up a local dev env with VS Studio next week

**Comment by hmaarrfk** [comment]
I think i'm hitting this bug.

Is this any worse than the old build, we can try building this
https://github.com/conda-forge/vigra-feedstock/pull/63

**Comment by k-dominik** [comment]
this is a bit of a weird one for me. When I build the recipe locally, I'll end up with a proper release build on win

**Comment by k-dominik** [comment]
superseeded by #17

**Pull request closed without merging**
