### PR TITLE
Try building shared libraries on windows

### PR DESCRIPTION
**Pull request by hmaarrfk**
@conda-forge-admin please rerender
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by k-dominik** [comment]
hi @hmaarrfk , the official lemon source mirror seems to be down. I have mirrored it on github and you could add it for the time being:

```
{% set sha256 = "e3d7a204a6fdbde8fe87dbc1aa3fd0ae58f908e9fbe8db8a6618db7cd44cdce6" %}

  url: https://github.com/k-dominik/lemon/archive/{{ version }}.tar.gz

```

**Comment by jakirkham** [comment]
Normally we just add the source tarball as a GitHub release on the feedstock in that case.

**Comment by k-dominik** [comment]
> Normally we just add the source tarball as a GitHub release on the feedstock in that case.

Thank you for the advice! I even found the original source tarball on an old machine. But I don't think I can just upload something here to be a release. Or at least I don't see it. Could you maybe point me to the right direction?

**Comment by hmaarrfk** [comment]
i think what i need is: https://github.com/conda-forge/lemon-feedstock/pull/16

**Comment by k-dominik** [comment]
> i think what i need is: #16

that, too, but currently the ci here fails because the lemon source is not available anymore

**Comment by hmaarrfk** [comment]
got it.

**Comment by k-dominik** [comment]
hey @hmaarrfk, I opened a PR to this branch with a fix (at least it fixes it for me locally).

**Comment by hmaarrfk** [comment]
thanks for reminding of that flag. If the project was still active, we should make the PR to upstream to export things correctly.

**Comment by k-dominik** [comment]
> thanks for reminding of that flag. If the project was still active, we should make the PR to upstream to export things correctly.

we can always start maintaining our own fork :D

**Comment by hmaarrfk** [comment]
> we can always start maintaining our own fork :D

understatement of the year.

**Comment by k-dominik** [comment]
let's hope that this somehow also fixes the debug issue, so #16 can be closed.

**Comment by k-dominik** [comment]
gee, i guess the following applies:

> For global data symbols, __declspec(dllimport) must still be used when compiling against the code in the .dll

**Comment by k-dominik** [comment]
I'll start working on a patch.

**Comment by k-dominik** [comment]
jeez...

**Comment by hmaarrfk** [comment]
hehe, maybe make your own PR if you plan on iterating ;)

**Comment by k-dominik** [comment]
Hi @hmaarrfk, 

> hehe, maybe make your own PR if you plan on iterating ;)

that at least takes the burden off of you to check every iteration. I can currently even reproduce the problem. Before I was building with VS, on conda-forge it's using ninja. If I use ninja locally, I at least see the same error. If I find something I will open a PR to this one, one last time, otherwise, will open my own pr, okay?

**Comment by hmaarrfk** [comment]
You can open as many PRs to my branch as you wish.

**Comment by k-dominik** [comment]
@bluescarni this is ready to be reviewed. Would be cool if you had a look.

**Comment by k-dominik** [comment]
do we have a fallback in case @bluescarni doesn't react? I wouldn't want to review a PR where I have contributed so much. @hmaarrfk @jakirkham ?

**Comment by k-dominik** [comment]
@hmaarrfk, I found some tiny issues with this PR when building vigra. I propose to close this one. I'll reopen a new PR that is a little more readable tomorrow

**Comment by hmaarrfk** [comment]
k

**Comment by jakirkham** [comment]
As to reviewers, circumstances for people change (like changing jobs, etc.). So it's natural for the maintainer list to evolve organically. If there are people interested in maintaining, happy to help facilitate that 🙂

Thanks for checking how this works with `vigra`

**Pull request closed without merging**
