### PR TITLE
Build shared libraries

### PR DESCRIPTION
**Pull request by stuarteberg**
See #1.

### CODE REVIEW

**Comment by stuarteberg** [comment]
Not sure what's wrong with the windows build.  Will need to investigate later, or punt it for now and build with static libs on Windows.  Note to self: there may be useful hints in this lemon recipe:
https://github.com/ilastik/ilastik-build-conda/tree/toolset-config/lemon

**Comment by jakirkham** [comment]
> build with static libs on Windows

This seems sensible. Not that the other options don't. Just that we are already building static libraries on Windows. So it is just a no change for now.

**Comment by jakirkham** [comment]
As a side note, is there any value in having static libraries? It seems the LEMON developers prefer these based on their build script, but I don't know if there are actual use cases that need static libraries as opposed to dynamics one.

Also ask this because if we don't ship static libraries and people were dependent on them, we might be hearing about breakage down the line. Just something to think about.

**Comment by jakirkham** [comment]
Also it is worth noting that on Windows one builds both a DLL and a LIB for shared libraries. So that may be part of the issue that the Windows build is seeing here.

ref: https://stackoverflow.com/questions/16737347/shared-libraries-windows-vs-linux-method

**Comment by jakirkham** [comment]
Have you ever tried doing this on Windows, @bluescarni?

**Comment by jakirkham** [comment]
cc @hmaarrfk (for awareness)

**Comment by hmaarrfk** [comment]
seems like this package needs a bit of TLC

**Pull request merged**
